### ISSUE TITLE
Playtesting

### ISSUE THREAD

**Issue by neokken** [kuroxy/SoulSweep#25]
Gijs
- [x] everything should be faster  (see more at #26)
- [x] Hitbox of player not aligning with sprite

Lucas
- [ ] Extra level
- [ ] Extra devourer ( needs to be harder, too easy to dodge him)
- [ ] Special Souls different color

Olaf
- [ ] No full screen (Also weird console in the background)
- [x] Sprinting (stamina bar?)  (see more at #26)

Tijs
- [x] Also sprinting (see more at #26)
- [x] Escape menu / pause menu

Jeremiah
- [ ] main menu button with the mouse                     
- [ ] fog of war bug?
- [x] escape button                      
- [x] #26

**Comment by neokken** [comment]
Escape button now goes back one menu, instead of instantly closing the application.

**Comment by neokken** [comment]
Hitbox problem solved moved the sprite 5 pixels up, now the feet align with the hitbox. Head does stick out but if you wall up it looks fine/ like there is some perspective

**Comment by neokken** [comment]
Dash has been implemented
